# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        version: [3.11, 3.12, 3.13]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: "5.12.0"

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v3.2.1

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - uses: yezz123/setup-uv@v4
      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run unit tests
        run: |
          uv run pytest

  deploy-dev:
    needs: 
      - build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Dev
        run: echo "Deploying to Dev..."
        env:
          SECRET: ${{ secrets.API_SECRET }}

  deploy-staging:
    needs: 
      - build
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Stg
        run: echo "Deploying to Stg..."
        env:
          SECRET: ${{ secrets.API_SECRET }}

  deploy-prod:
    needs: 
      - build
      - deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Prod
        run: echo "Deploying to Prod..."
        env:
          SECRET: ${{ secrets.API_SECRET }}